version: '3.8'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: agro_db
    volumes:
      - /home/dev/volumes/agro_db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  localdb:
